apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-customer
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp-customer
        image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-admin
  template:
    metadata:
      labels:
        app: webapp-admin
    spec:
      containers:
      - name: webapp-admin
        image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-customer
  labels:
    app: webapp-customer
spec:
  ports:
  - port: 80
  selector:
    app: webapp-customer
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-admin
  labels:
    app: webapp-admin
spec:
  ports:
  - port: 80
  selector:
    app: webapp-admin